version: "3.7"
services:
  web_flask:
    build:
      context: ./flaskr
      args:
        project_directory: "/flaskr/"
    ports:
      - "5000:5000"
    volumes:
      - "./flaskr:/flaskr"
    environment:
      TZ: "Asia/Tokyo"
      FLASK_APP: "."
      FLASK_ENV: "development"
    tty: true
